[versions]
accompanist = "0.33.2-alpha"
activity-compose = "1.8.1"
agp = "8.2.0"
androidx-test-ext-junit = "1.1.5"
ben-manes-versions = "0.49.0"
coil = "2.5.0"
compileSdk = "34"
compose-bom = "2023.10.01"
core-ktx = "1.12.0"
core-splashscreen = "1.0.1"
espresso-core = "3.5.1"
gradle-ktlint = "11.6.1"
hilt = "2.48.1"
hilt-navigation-compose = "1.1.0"
junit = "4.13.2"
kotlin = "1.9.20"
kotlinCompilerExtensionVersion = "1.5.5"
ksp = "1.9.20-1.0.14"
lifecycle-runtime-ktx = "2.7.0-rc01"
material3 = "1.2.0-alpha12"
minSdk = "26"
paging = "3.2.1"
palette = "1.0.0"
retrofit2 = "2.9.0"
targetSdk = "34"
version-catalog-update = "0.8.1"

[libraries]
accompanist-adaptive = { module = "com.google.accompanist:accompanist-adaptive", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-material3-window = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette" }
squareup-retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradle-ktlint" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }

[bundles]
compose = [
    "compose-material-icons-extended",
    "compose-material3",
    "compose-material3-window",
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-tooling-preview",
    "compose-ui-util",
]
hilt = [
    "hilt-android",
    "hilt-navigation-compose",
]
retrofit2 = [
    "squareup-retrofit2-converter-gson",
    "squareup-retrofit2-retrofit",
]
